services:
  - type: web
    name: jarvis-web
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: FLASK_SECRET
        value: your_secret_key_here
